language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script:
  - phpunit --colors --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls --verbose
