# Application
debug: true;

# Doctrine
# pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_ibm, pdo_sqlsrv
doctrine.drive: pdo_sqlite
# doctrine.dbname: database
# doctrine.host: localhost
# doctrine.user: user
# doctrine.password: password
# pdo_mysql, and pdo_oci/oci8
# doctrine.charset: UTF8
# pdo_sqlite
doctrine.path: %app.root_dir%/app_dev.db
# pdo_mysql, pdo_pgsql, pdo_oci/oci8
# doctrine.port: 3306

# Monolog
monolog.logfile: %app.root_dir%/app/logs/dev.log

# Silex Web Profiler
profiler.cache_dir: %app.root_dir%/app/cache/profiler
profiler.mount_prefix: /_profiler
