%locale%: en

# Application
route_class: App\Route
locale: %locale%
charset: UTF-8

# Session
session.default_locale: %locale%

# Translation
locale_fallbacks: [en]

# Twig
twig.path: %app.root_dir%/app/Resources/views

# Monolog
monolog.name: App;

# Swift Mailer
swiftmailer.options:
  extraparams: -f%s
