# Application
debug: true;

# Doctrine
db.options:
  # pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_ibm, pdo_sqlsrv
  driver: pdo_sqlite
  # dbname: database
  # host: localhost
  # user: user
  # password: password
  # pdo_mysql, and pdo_oci/oci8
  # charset: UTF8
  # pdo_sqlite
  path: %app.root_dir%/app_dev.db
  # pdo_mysql, pdo_pgsql, pdo_oci/oci8
  # port: 3306

# Monolog
monolog.logfile: %app.root_dir%/app/logs/dev.log

# Silex Web Profiler
profiler.cache_dir: %app.root_dir%/app/cache/profiler
profiler.mount_prefix: /_profiler
