# Application
route_class: App\Route
locale: en
charset: UTF-8

# Translation
locale_fallbacks: [en]

# Twig
twig.path: %app.root_dir%/app/Resources/views

# Monolog
monolog.name: App;

# Swift Mailer
swiftmailer.options:
  extraparams: -f%s
