default_home:
  methods: [GET]
  path: /
  defaults:
    _controller: App\DefaultBundle\Controller\PageController::show
    slug: index

default_page:
  methods: [GET]
  path: /{slug}
  defaults:
    _controller: App\DefaultBundle\Controller\PageController::show
  requirements:
    slug: .+
